'use strict';
var boardElement = document.getElementById('board');
var resetButton = document.getElementById('reset-btn');
var startGameButton = document.getElementById('start-game');
var modalRestart = document.getElementById('modal-restart');
var difficultySelect = document.getElementById('difficulty');
var resultModal = document.getElementById('result-modal');
var resultMessage = document.getElementById('result-message');
var nameWarningModal = document.getElementById('name-warning-modal');
var closeNameWarning = document.getElementById('close-name-warning');
var playerNameInput = document.getElementById('player-name');
var nameError = document.getElementById('nameError');
var flagCounter = document.querySelector('.flag-counter');
var timerElement = document.querySelector('.timer');
var board = [];
var revealed = [];
var flagged = [];
var size = 8;
var mineCount = 10;
var gameStarted = false;
var gameOver = false;
var timer;
var seconds = 0;
var soundVictory = new Audio('sounds/victory.mp3');
var soundDefeat = new Audio('sounds/defeat.mp3');
soundDefeat.volume = 0.3;
soundVictory.volume = 0.3;